# bambot/templates/Dockerfile.j2
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY {{ bot_file }} ./
COPY bambot/ bambot/

CMD ["python", "-m", "bambot.agent", "--bot-file={{ bot_file }}"]