# bambot/templates/Dockerfile.lightweight.j2
FROM python:3.9-alpine
WORKDIR /app

# Install the required packages
RUN apk add --no-cache \
    build-base \
    musl-dev \
    libffi-dev

# Copy the bot file from the build context
COPY {{ bot_file }} ./

# Install additional packages from requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Remove the build dependencies
RUN apk del \
    build-base \
    musl-dev \
    libffi-dev

# Set the PYTHONUNBUFFERED environment variable to ensure real-time output
ENV PYTHONUNBUFFERED=1

# Disable Python's generation of .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# Copy the run script
COPY run.sh ./

# Make the run script executable
RUN chmod +x run.sh

# Start the agent
CMD ["./run.sh"]