# bambot/templates/Dockerfile.dashboard.j2
FROM python:3.9-bullseye

WORKDIR /app

# Install required packages for pyarrow
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install required packages for the app
RUN pip install --no-cache-dir click tqdm jinja2 requests

# Copy the requirements.txt file if it exists, otherwise create an empty file
COPY requirements.txt* ./
RUN touch requirements.txt

# Install additional packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir "pyarrow==10.0.1" \
    && pip install --no-cache-dir streamlit

# Copy the bot file and bambot directory
COPY bot.py ./
COPY bambot/ bambot/

# Set the PYTHONUNBUFFERED environment variable to ensure real-time output
ENV PYTHONUNBUFFERED=1

# Disable Python's generation of .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8501

# Copy the run script
COPY run.sh /app/run.sh

# Make the run script executable
RUN chmod +x /app/run.sh

# Start the agent and Streamlit dashboard
CMD ["/app/run.sh"]