# bambot/templates/Dockerfile.j2
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt {{ bot_file }} ./
COPY bambot/ bambot/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "bambot/container_script.py", "--bot-file={{ bot_file }}"]